import type { Metadata } from "next";

import "./globals.css";

import RecoilProvider from "@/lib/RecoilProvider";
import NavBar from "@/app/components/navBar";

export const metadata: Metadata = {
  title: "MyDashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-slate-950 text-white">
      <RecoilProvider>
        <body>
          <NavBar />
          {children}
        </body>
      </RecoilProvider>
    </html>
  );
}
